install.packages("rstudioapi")
install.packages("devtools")
install.packages("shinyWidgets")
install.packages("shiny")
install.packages("RcppArmadillo")
install.packages("RcppAlgos")
install.packages("rsvg")
install.packages("forcats")
install.packages("reshape2")
install.packages("plotly")
install.packages(c("sf", "stars", "rnaturalearth"))
install.packages("forcats")

devtools::install_github("bodkan/slendr")
devtools::install_github("bodkan/demografr")
