// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// sum_nan_cpp
double sum_nan_cpp(const arma::mat& M);
RcppExport SEXP _prehistorir_sum_nan_cpp(SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type M(MSEXP);
    rcpp_result_gen = Rcpp::wrap(sum_nan_cpp(M));
    return rcpp_result_gen;
END_RCPP
}
// mat_prod
arma::mat mat_prod(arma::mat& A, arma::mat& B);
RcppExport SEXP _prehistorir_mat_prod(SEXP ASEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(mat_prod(A, B));
    return rcpp_result_gen;
END_RCPP
}
// sample_next_xy
int sample_next_xy(arma::mat& M);
RcppExport SEXP _prehistorir_sample_next_xy(SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type M(MSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_next_xy(M));
    return rcpp_result_gen;
END_RCPP
}
// select_row
arma::mat select_row(arma::mat& M, arma::uvec& v);
RcppExport SEXP _prehistorir_select_row(SEXP MSEXP, SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type M(MSEXP);
    Rcpp::traits::input_parameter< arma::uvec& >::type v(vSEXP);
    rcpp_result_gen = Rcpp::wrap(select_row(M, v));
    return rcpp_result_gen;
END_RCPP
}
// extract_neighbourhood_cpp
arma::mat extract_neighbourhood_cpp(arma::mat& map_mat, const int& x, const int& y, const int& radius);
RcppExport SEXP _prehistorir_extract_neighbourhood_cpp(SEXP map_matSEXP, SEXP xSEXP, SEXP ySEXP, SEXP radiusSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type map_mat(map_matSEXP);
    Rcpp::traits::input_parameter< const int& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const int& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const int& >::type radius(radiusSEXP);
    rcpp_result_gen = Rcpp::wrap(extract_neighbourhood_cpp(map_mat, x, y, radius));
    return rcpp_result_gen;
END_RCPP
}
// define_spawn_map
arma::mat define_spawn_map(arma::mat& conv_map_mat, arma::mat& live_map_mat, const int& x, const int& y, const int& radius);
RcppExport SEXP _prehistorir_define_spawn_map(SEXP conv_map_matSEXP, SEXP live_map_matSEXP, SEXP xSEXP, SEXP ySEXP, SEXP radiusSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type conv_map_mat(conv_map_matSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type live_map_mat(live_map_matSEXP);
    Rcpp::traits::input_parameter< const int& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const int& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const int& >::type radius(radiusSEXP);
    rcpp_result_gen = Rcpp::wrap(define_spawn_map(conv_map_mat, live_map_mat, x, y, radius));
    return rcpp_result_gen;
END_RCPP
}
// check_neighbourhood_cpp
bool check_neighbourhood_cpp(arma::mat& M, const double& ratio);
RcppExport SEXP _prehistorir_check_neighbourhood_cpp(SEXP MSEXP, SEXP ratioSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type M(MSEXP);
    Rcpp::traits::input_parameter< const double& >::type ratio(ratioSEXP);
    rcpp_result_gen = Rcpp::wrap(check_neighbourhood_cpp(M, ratio));
    return rcpp_result_gen;
END_RCPP
}
// check_spawn_map_cpp
bool check_spawn_map_cpp(arma::mat& M);
RcppExport SEXP _prehistorir_check_spawn_map_cpp(SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type M(MSEXP);
    rcpp_result_gen = Rcpp::wrap(check_spawn_map_cpp(M));
    return rcpp_result_gen;
END_RCPP
}
// make_binary
arma::mat make_binary(arma::mat& M, const bool& keep_na);
RcppExport SEXP _prehistorir_make_binary(SEXP MSEXP, SEXP keep_naSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type M(MSEXP);
    Rcpp::traits::input_parameter< const bool& >::type keep_na(keep_naSEXP);
    rcpp_result_gen = Rcpp::wrap(make_binary(M, keep_na));
    return rcpp_result_gen;
END_RCPP
}
// convolve_mat_full_cpp
arma::mat convolve_mat_full_cpp(arma::mat& M, arma::mat& kernel);
RcppExport SEXP _prehistorir_convolve_mat_full_cpp(SEXP MSEXP, SEXP kernelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type M(MSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type kernel(kernelSEXP);
    rcpp_result_gen = Rcpp::wrap(convolve_mat_full_cpp(M, kernel));
    return rcpp_result_gen;
END_RCPP
}
// convert_xy_new
IntegerVector convert_xy_new(const int& x_par, const int& y_par, const int& x_new, const int& y_new, const int& radius);
RcppExport SEXP _prehistorir_convert_xy_new(SEXP x_parSEXP, SEXP y_parSEXP, SEXP x_newSEXP, SEXP y_newSEXP, SEXP radiusSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int& >::type x_par(x_parSEXP);
    Rcpp::traits::input_parameter< const int& >::type y_par(y_parSEXP);
    Rcpp::traits::input_parameter< const int& >::type x_new(x_newSEXP);
    Rcpp::traits::input_parameter< const int& >::type y_new(y_newSEXP);
    Rcpp::traits::input_parameter< const int& >::type radius(radiusSEXP);
    rcpp_result_gen = Rcpp::wrap(convert_xy_new(x_par, y_par, x_new, y_new, radius));
    return rcpp_result_gen;
END_RCPP
}
// update_conv_map_mat_cpp
void update_conv_map_mat_cpp(arma::mat& conv_map_mat, arma::mat& map_mat, arma::mat& kernel, const int& x, const int& y, const int& radius);
RcppExport SEXP _prehistorir_update_conv_map_mat_cpp(SEXP conv_map_matSEXP, SEXP map_matSEXP, SEXP kernelSEXP, SEXP xSEXP, SEXP ySEXP, SEXP radiusSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type conv_map_mat(conv_map_matSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type map_mat(map_matSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type kernel(kernelSEXP);
    Rcpp::traits::input_parameter< const int& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const int& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const int& >::type radius(radiusSEXP);
    update_conv_map_mat_cpp(conv_map_mat, map_mat, kernel, x, y, radius);
    return R_NilValue;
END_RCPP
}
// bd_loop
void bd_loop(NumericMatrix& pop_mat, arma::mat& map_mat, arma::mat& conv_map_mat, arma::mat& live_map_mat, arma::mat& kernel, const NumericVector& pop_ids, const NumericVector& sampled_events, const NumericVector& N, const int& radius, NumericVector& next_pop_v, const int& offset, NumericVector& n_v, const int& n_max, const int& t, NumericVector& i_mat_v);
RcppExport SEXP _prehistorir_bd_loop(SEXP pop_matSEXP, SEXP map_matSEXP, SEXP conv_map_matSEXP, SEXP live_map_matSEXP, SEXP kernelSEXP, SEXP pop_idsSEXP, SEXP sampled_eventsSEXP, SEXP NSEXP, SEXP radiusSEXP, SEXP next_pop_vSEXP, SEXP offsetSEXP, SEXP n_vSEXP, SEXP n_maxSEXP, SEXP tSEXP, SEXP i_mat_vSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix& >::type pop_mat(pop_matSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type map_mat(map_matSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type conv_map_mat(conv_map_matSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type live_map_mat(live_map_matSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type kernel(kernelSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type pop_ids(pop_idsSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type sampled_events(sampled_eventsSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type N(NSEXP);
    Rcpp::traits::input_parameter< const int& >::type radius(radiusSEXP);
    Rcpp::traits::input_parameter< NumericVector& >::type next_pop_v(next_pop_vSEXP);
    Rcpp::traits::input_parameter< const int& >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< NumericVector& >::type n_v(n_vSEXP);
    Rcpp::traits::input_parameter< const int& >::type n_max(n_maxSEXP);
    Rcpp::traits::input_parameter< const int& >::type t(tSEXP);
    Rcpp::traits::input_parameter< NumericVector& >::type i_mat_v(i_mat_vSEXP);
    bd_loop(pop_mat, map_mat, conv_map_mat, live_map_mat, kernel, pop_ids, sampled_events, N, radius, next_pop_v, offset, n_v, n_max, t, i_mat_v);
    return R_NilValue;
END_RCPP
}
// conv_2d_cpp
arma::mat conv_2d_cpp(const arma::mat& pad, const arma::mat& kernel);
RcppExport SEXP _prehistorir_conv_2d_cpp(SEXP padSEXP, SEXP kernelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type pad(padSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type kernel(kernelSEXP);
    rcpp_result_gen = Rcpp::wrap(conv_2d_cpp(pad, kernel));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_prehistorir_sum_nan_cpp", (DL_FUNC) &_prehistorir_sum_nan_cpp, 1},
    {"_prehistorir_mat_prod", (DL_FUNC) &_prehistorir_mat_prod, 2},
    {"_prehistorir_sample_next_xy", (DL_FUNC) &_prehistorir_sample_next_xy, 1},
    {"_prehistorir_select_row", (DL_FUNC) &_prehistorir_select_row, 2},
    {"_prehistorir_extract_neighbourhood_cpp", (DL_FUNC) &_prehistorir_extract_neighbourhood_cpp, 4},
    {"_prehistorir_define_spawn_map", (DL_FUNC) &_prehistorir_define_spawn_map, 5},
    {"_prehistorir_check_neighbourhood_cpp", (DL_FUNC) &_prehistorir_check_neighbourhood_cpp, 2},
    {"_prehistorir_check_spawn_map_cpp", (DL_FUNC) &_prehistorir_check_spawn_map_cpp, 1},
    {"_prehistorir_make_binary", (DL_FUNC) &_prehistorir_make_binary, 2},
    {"_prehistorir_convolve_mat_full_cpp", (DL_FUNC) &_prehistorir_convolve_mat_full_cpp, 2},
    {"_prehistorir_convert_xy_new", (DL_FUNC) &_prehistorir_convert_xy_new, 5},
    {"_prehistorir_update_conv_map_mat_cpp", (DL_FUNC) &_prehistorir_update_conv_map_mat_cpp, 6},
    {"_prehistorir_bd_loop", (DL_FUNC) &_prehistorir_bd_loop, 15},
    {"_prehistorir_conv_2d_cpp", (DL_FUNC) &_prehistorir_conv_2d_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_prehistorir(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
