## ---------------------------
##
##
## Purpose of script: This script contains all the functions that have the purpose
## of generating/creating models based on birth-death processes
##
## Author: Filippo Tell
##
## Date Created: 2026-01-29
##
##
## ---------------------------
##
## Notes: many functions are similar/have the same structures. These
## are intermidiates steps that I created while I was trying to understand
## how to structure a more general function. I will probably remove lots of stuff later on
##
##
## ---------------------------

# function to check that a jolly event has the correct structure
# i.e. first element is an integer, second a function
# return boolean
check_event <- function(event){
  # check first element, has to be a time point
  el_1 <- is.double(event[[1]]) && (event[[1]]>0)
  # check second element (needs to be a function)
  el_2 <- is.function(event[[2]])
  return(all(el_1, el_2))
}

# European colonization version -------------------------------------------


# Rcpp version

# Function to create a model that populates Europe through a birth-death process
# The way this function works is: we simply go through each generation and at each generation
# we decide which event is going to happen. For now we have three events:
# - Birth
# - Death
# - Nothing happens
# The events are mutually exclusive and in each generation one of these three events happens, sampled with a certain prob that is passed as an argument

#' Create a prehistorir metapopulation model
#'
#' Function to create a spatial metapopulation model that undergoes extinction and recolonization dynamics according to a
#' given birth and death rate.
#'
#' @param b Birth rate. Probability that a tribe give rise to a population.
#' @param d Death rate. Probability that a tribe dies.
#' @param t_start Time at which the metapopulation model starts.
#' @param t_stop Time at which the metapopulation model stops.
#' @param map_mat Object of the \code{prehistorik_map} class generated by the function \code{get_map_as_matrix}.
#' @param live_map_3d Liveability map in 3D, where each layer correspond to one generation of the model.
#' @param start_pop_mat Matrix corresponding to the starting populations.
#' @param generation_time Generation time in years.
#' @param jolly
#' @param N Either a function or a constant, corresponding to the number of individuals for each new tribe.
#' @param radius Radius within which a new tribe can be spawned.
#' @param kernel (optional) Kernel used by the convolution to establish the number of tribes in a neighbourhood. If not provided a standard kernel will be generated.
#' @param n_max Maximum number of tribes that can simultaneously live in the model.
#' @param ...
#'
#' @returns An object of the class \code{prehistorik_model}, which corresponds to a data frame containing the history of the metapopulation.
#' @export
#'
create_prehistorik_model_cpp <- function(start_pop_mat, map_mat, b=1, d=0, t_start=1e6, t_stop=0, live_map_3d, generation_time = 30, jolly = NULL, N=NULL, radius=NULL, kernel=NULL, n_max=NULL, ...){
  if(!inherits(map_mat, "prehistorik_map")) stop("map_mat do not belong to the class prehistorik_map.\n Are you sure you use the function get_map_as_matrix to generate it?")
  if (is.null(N)) {
    stop("You did not provide any N value. It needs to be either a constant or a function.")
  }
  if (is.null(kernel)) {
    warning("You did not provide any kernel")
    kernel <- generate_kernel(radius = radius)
  }else{
    warning("Since you provided a kernel, the argument radius will be ignored.")
  }
  # establish the radius of the neighbourhood based on the kernel size
  radius <- (dim(kernel)[1]-1)/2
  if (n_start<1) stop("The starting number of populations has to be strictly positive.")

  if(b<0 || d<0 || b+d>1){
    stop("The birth/death rates should be probabilities.")
  }
  # check if the users provided special events
  # the jolly variable should be a list of two elements sublist
  # (see later to better understand)
  if(!is.null(jolly)){
    # the first element of each sublist should correspond to the time
    # when that event is occurring, the event should be a function
    # check the structure of the list
    if(!all(sapply(jolly, check_event))){
      stop("The list of events provided do not have the correct structure.")
    }
    # extract the timing of these event and check that the timing is correct
    # i.e. two events do not collide with each other and their timing
    # fall within the provided interval
    events_times <- sapply(jolly, function(x) x[[1]])
    if(!all(diff(events_times)>=2*generation_time) || events_times>t_start ||  events_times<t_stop)
      stop("The timing of the special events is not correct.")
  }

  # create a copy of map_mat so to not modify the original
  # in rcpp
  # actually it does not work
  map_mat_cpp <- map_mat
  # maximum number of pops, defined by the number of not occupied cells by african pop
  # cell in the map_mat_cpp if not given
  if(is.null(n_max)) n_max <- sum(map_mat_cpp!=0, na.rm = T)
  # preinitialize a matrix and
  # make it at least as three times the maximum number of the population
  pop_mat <- matrix(0, ncol = 9, nrow = 3*n_max)
  pop_mat <- rbind(start_pop_mat, pop_mat)
  # initial number of real pop is equal to the highest number of the pop
  n <- max(pop_mat[,2])
  # store the next index to access the dataframe
  i_mat <- nrow(start_pop_mat)+1
  # introduce an offset that tells where the non ancestral population
  # are (ancestral are saved as 0) --> they are placed at teh satrt of this matrix
  offset <- sum(start_pop_mat[,2]==0)
  # if not provided pick the minimum t_start of the pop in the df
  if(is.null(t_start)) t_start <- min(pop_mat[,3], na.rm = TRUE)
  t <- t_start
  # time at any point in the tree
  next.pop <- n+1
  # save attributes of the map to add them back later, as they will be used
  # in the rcpp loop
  resolution <- get_resolution(map_mat_cpp)
  crs <- get_crs(map_mat_cpp)
  bbox <- get_bbox(map_mat_cpp)
  # NOTE: THIS CAN BE DONE HERE
  # CAUSE THEN WE WILL WORK ON THEM BY REFERENCE
  # HOWEVER THIS CAN INTRODUCE SOME PROBLEMS IF THERE ARE SOME JOLLY EVENTS
  # IN THAT CASE WE MIGHT WANT TO REPEAT THIS OPERATION
  # NO PROBLEM FOR NOW
  # convolve map
  conv_map_mat <- convolve_mat_full_cpp(map_mat_cpp, kernel)
  # make bianry map
  # bin_map_mat <- make_binary(map_mat_cpp, keep_na = TRUE)
  ####################
  # BIRTH-DEATH LOOP #
  ####################
  repeat {
    # update t subtracting generation_time to t
    t <- t - generation_time
    # check whether t is less than the t_end; in that case exit
    if (t <= t_stop)
      break
    # first check if there are any jolly events
    if(!is.null(jolly)){
      # check whether there is an event happening nearby this t
      is_happening <- (events_times-t<generation_time) & (events_times-t>=0)
      if(any(is_happening)){
        # pick that event as the event happening
        # second element is a function
        event <- jolly[[which(is_happening)]][[2]]
        # make it happen
        event()
        next
      }
    }
    # if there are no jolly events happening
    # establish some events that could happen at each generation, e.g.:
    # birth
    # death
    # nothing
    # for each active and alive population establish what it is going to happen for it
    # shuffle them so not to be biased in the order
    # 5 is alive, 9 active
    pop_ids <- sample(pop_mat[intersect(which(pop_mat[,5]==1), which(pop_mat[,9]==1)), 2])
    # check if the pop_mat has enough space left to fit a strike of all births
    if((nrow(pop_mat)-i_mat)<=length(pop_ids)) pop_mat <- rbind(pop_mat, matrix(0, ncol = 9, nrow = 5*n_max))
    # c("b", "d", "n") ---> 1,2,3
    events <- 1:3
    # decide which type of event is going to happen in this new t point:# sample according to the probabilities of each event
    # to decide which event is happening
    # sample already the all list of event for each population (I guess it speeds up a bit)
    sampled_events <- sample(events, size = length(pop_ids), prob = c(b, d, 1 - b - d), replace = TRUE)
    # remove in advance the pop_ids that are not going to change
    # browser()
    pop_ids <- pop_ids[sampled_events!=3]
    sampled_events <- sampled_events[sampled_events!=3]

    # if there are no events skip this
    if(length(pop_ids)==0) next

    # IF N IS A FUNCTION AND VECTORIZIBLE THIS CAN BE SPEED UP
    if (is.function(N)) {
      # N_pop <- sapply(1:length(pop_ids), function(x) N(...))
      N_pop <- N(length(pop_ids))
    } else{
      N_pop <- rep(N, length(pop_ids))
    }

    # pass everything to the rcpp function
    ######################################
    ###########  BD-LOOP  ################
    ######################################
    bd_loop(
      pop_mat = pop_mat,
      map_mat = map_mat_cpp,
      conv_map_mat = conv_map_mat,
      live_map_mat = live_map_3d[ , , as.character(t)],
      kernel = kernel,
      pop_ids = pop_ids,
      sampled_events = sampled_events,
      N = N_pop,
      radius = radius,
      next_pop_v = next.pop,
      offset = offset,
      n_v = n,
      n_max = n_max,
      t = t,
      i_mat_v = i_mat
    )
  }
  # remove 0s part of the df
  pop_mat <- pop_mat[1:(i_mat-1),]
  model <- as.data.frame(pop_mat)
  names(model) <-c("parent", "pop", "t_start", "t_end", "alive", "x", "y", "N", "active")
  model$alive <- as.logical(model$alive)
  model$active <- as.logical(model$active)
  # store all the parameters
  parameters <- list(
    radius = radius,
    b_rate = b,
    d_rate = d,
    N = N,
    generation_time = generation_time,
    t_start = t_start,
    t_stop = t_stop,
    kernel = kernel,
    time_points = seq(t_start, t_stop, -generation_time)
  )
  attr(model, "map_mat") <- map_mat_cpp
  attr(model, "parameters") <- parameters
  # set class
  class(model) <- set_class(model, "model")
  return(model)
}
