## ---------------------------
##
##
## Purpose of script: This script contains functions that might be generally useful
##
## Author: Filippo Tell
##
## Date Created: 2026-01-30
##
##
## ---------------------------
##
## Notes:
##
##
## ---------------------------


# function to create a gif

# create_gif_bw <- function(model, dir, file_name, rate=5){
#   if(!inherits(model, "prehistorik_model")) stop("model do not belong to the class prehistorik_model\n Are you sure you use the function create_prehistorik_model to generate it?")
#   unlink(dir, recursive = TRUE)
#   dir.create(dir, recursive = T)
#   param <- get_parameters(model)
#   times <- seq(param$t_start, param$t_stop, -param$generation_time)
#   parallel::mclapply(seq(1, length(times), rate), function(i) {
#     time <- times[i]
#     p_pop <- plot_map_slice(model, time = time)+theme(legend.position = "none")
#     ggsave(filename = sprintf("%s/%s%s%s.jpg", dir, file_name, paste0(rep(0,5-nchar(i)), collapse = ""), i), plot = p_pop, width = 14, height = 9)
#   }, mc.cores = 8)
#   if(Sys.which("convert")=="") stop("The binary convert is not present.\nYou must install ImageMagick")
#   system(sprintf("convert -delay 40 -loop 0 -resize 100%% %s/%s*.jpg %s/%s.gif", dir, file_name, dir, file_name))
#
#   unlink(sprintf("%s/%s*.jpg", dir, file_name), recursive = TRUE)
# }


# Set classes (or fix their priorities if already present)
set_class <- function(x, type) {
  other_classes <- class(x)
  c(paste0("prehistorik_", type), other_classes)
}


# extract attributes from prehistorik objects -----------------------------


get_crs <- function(obj){
  if(inherits(obj, "prehistorik_map")) attr(obj, "crs")
  else if(inherits(obj, "prehistorik_model")) get_crs(attr(obj, "map_mat"))
  else stop("The object is not neither of the class prehistorik_map or prehistorik_model." )
}

get_bbox <- function(obj){
  if(inherits(obj, "prehistorik_map")) attr(obj, "bbox")
  else if(inherits(obj, "prehistorik_model")) get_bbox(attr(obj, "map_mat"))
  else stop("The object is not neither of the class prehistorik_map or prehistorik_model." )
}

get_resolution <- function(obj){
  if(inherits(obj, "prehistorik_map")) attr(obj, "resolution")
  else if(inherits(obj, "prehistorik_model")) get_resolution(attr(obj, "map_mat"))
  else stop("The object is not neither of the class prehistorik_map or prehistorik_model." )
}

get_parameters <- function(obj){
  if(inherits(obj, "prehistorik_model")) attr(obj, "parameters")
}

get_generation_time <- function(obj){
  if(inherits(obj, "prehistorik_model")) {
    parameters <- get_parameters(obj)
    parameters$generation_time
  }else stop("The object is not a prehistorik_model. Are you sure it was generated by the function create_prehistorik_model?")
}

get_radius <- function(obj){
  if(inherits(obj, "prehistorik_model")) {
    parameters <- get_parameters(obj)
    parameters$radius
  }else stop("The object is not a prehistorik_model. Are you sure it was generated by the function create_prehistorik_model?")
}

get_b_rate <- function(obj){
  if(inherits(obj, "prehistorik_model")) {
    parameters <- get_parameters(obj)
    parameters$b_rate
  }else stop("The object is not a prehistorik_model. Are you sure it was generated by the function create_prehistorik_model?")
}

get_d_rate <- function(obj){
  if(inherits(obj, "prehistorik_model")) {
    parameters <- get_parameters(obj)
    parameters$d_rate
  }else stop("The object is not a prehistorik_model. Are you sure it was generated by the function create_prehistorik_model?")
}

get_kernel <- function(obj){
  if(inherits(obj, "prehistorik_model")) {
    parameters <- get_parameters(obj)
    parameters$kernel
  }else stop("The object is not a prehistorik_model. Are you sure it was generated by the function create_prehistorik_model?")
}

get_map_mat <- function(obj){
  if(inherits(obj, "prehistorik_model")) {
    attr(obj, "map_mat")
  }else stop("The object is not a prehistorik_model. Are you sure it was generated by the function create_prehistorik_model?")
}

get_model <- function(obj){
  if(inherits(obj, "prehistorik_dist_df") || inherits(obj, "prehistorik_geneflows_df")) {
    attr(obj, "model")
  }else stop("The object is not a prehistorik_geneflows_df or prehistorik_dist_df. Are you sure it was generated by the functions?")
}

get_threshold <- function(obj){
  if(inherits(obj, "prehistorik_dist_df")) attr(obj, "threshold")
  else stop("The object is not of the class prehistorik_dist_df." )
}
